{% set name = "perpetual" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/perpetual-{{ version }}.tar.gz
  sha256: 99da22814ff6a1971ea5d6e58974426a1a265c8975ce511f2dd52b6c5544b382

build:
  skip: true  # [py<39]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0.0,<1.7.0
    - pip
  run:
    - python
    - numpy
    - typing_extensions

test:
  imports:
    - perpetual
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://perpetual-ml.com
  dev_url: https://github.com/perpetual-ml/perpetual
  doc_url: https://perpetual-ml.github.io/perpetual/
  summary: A self-generalizing gradient boosting machine which doesn't need hyperparameter optimization
  license: AGPL-3.0-only
  license_file:
    - LICENSE
    - python-package/LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - thewchan
    - deadsoul44
